# Generated by Django 2.0.7 on 2018-10-11 09:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mod_foncier.submodels.model_foncier_expertise
import mod_foncier.submodels.model_foncier_parcelle


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoncierAccessibilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoncierCaracteristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_batie', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FoncierCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoncierExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_expertise', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_foncier.submodels.model_foncier_expertise.path_dossier_expertise)),
                ('annee', models.PositiveSmallIntegerField()),
                ('superficie_non_batie', models.PositiveSmallIntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FoncierImpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impot', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accessibilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierAccessibilite')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierCategorie')),
            ],
        ),
        migrations.CreateModel(
            name='FoncierParcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcelle', models.CharField(max_length=15, unique=True)),
                ('numero_police', models.CharField(blank=True, max_length=15, null=True)),
                ('fichier_declaration', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_foncier.submodels.model_foncier_parcelle.path_fichier_declaration)),
                ('numero_carte_physique', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_impression', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Quartier')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
                ('numero_rueavenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.RueOuAvenue')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcelle_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcelle_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcelle_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcelle_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FoncierParcellePublique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcelle', models.CharField(max_length=15, unique=True)),
                ('adresse_precise', models.CharField(blank=True, max_length=255, null=True)),
                ('occupee', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Quartier')),
                ('numero_rueavenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.RueOuAvenue')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcellepublique_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcellepublique_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcellepublique_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcellepublique_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FoncierTnbCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoncierTnbImpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impot', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accessibilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierAccessibilite')),
                ('tnb_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierTnbCategorie')),
            ],
        ),
        migrations.CreateModel(
            name='FoncierTypeConfort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='foncierimpot',
            name='type_confort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierTypeConfort'),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='impot_non_batie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierTnbImpot'),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierParcelle'),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foncierexpertise_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierexpertise_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierexpertise_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierexpertise_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fonciercaracteristique',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierExpertise'),
        ),
        migrations.AddField(
            model_name='fonciercaracteristique',
            name='impot_batie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierImpot'),
        ),
        migrations.AlterUniqueTogether(
            name='fonciertnbimpot',
            unique_together={('tnb_categorie', 'accessibilite')},
        ),
        migrations.AlterIndexTogether(
            name='fonciertnbimpot',
            index_together={('tnb_categorie', 'accessibilite')},
        ),
        migrations.AlterUniqueTogether(
            name='foncierimpot',
            unique_together={('categorie', 'type_confort', 'accessibilite')},
        ),
        migrations.AlterIndexTogether(
            name='foncierimpot',
            index_together={('categorie', 'type_confort', 'accessibilite')},
        ),
        migrations.AlterUniqueTogether(
            name='foncierexpertise',
            unique_together={('parcelle', 'annee')},
        ),
        migrations.AlterIndexTogether(
            name='foncierexpertise',
            index_together={('parcelle', 'annee')},
        ),
        migrations.AlterUniqueTogether(
            name='fonciercaracteristique',
            unique_together={('expertise', 'impot_batie')},
        ),
        migrations.AlterIndexTogether(
            name='fonciercaracteristique',
            index_together={('expertise', 'impot_batie')},
        ),
    ]
