# Generated by Django 2.0.7 on 2018-10-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncierexpertise',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foncierparcelle',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foncierparcellepublique',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
