# Generated by Django 2.0.7 on 2018-10-26 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_foncier', '0002_auto_20181023_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncierexpertise',
            name='date_ecriture',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='user_ecriture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierexpertise_requests_ecriture', to=settings.AUTH_USER_MODEL),
        ),
    ]
