# Generated by Django 2.0.7 on 2018-11-15 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_foncier', '0009_foncierexpertise_date_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncierexpertise',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierexpertise_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foncierparcelle',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foncierparcelle',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcelle_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foncierparcellepublique',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foncierparcellepublique',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foncierparcellepublique_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
    ]
