# Generated by Django 2.0.7 on 2018-12-07 09:28

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0010_auto_20181115_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoncierAcroissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=datetime.date(1900, 1, 1))),
                ('date_fin', models.DateField(default=datetime.date(1900, 1, 1))),
                ('taux', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
