# Generated by Django 2.0.7 on 2018-12-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0011_foncieracroissement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoncierAcroissement',
            new_name='FoncierAccroissement',
        ),
    ]
