# Generated by Django 2.0.7 on 2018-12-09 18:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0012_auto_20181207_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncierexpertise',
            name='accroissement_montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='accroissement_taux',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
