# Generated by Django 2.0.7 on 2018-12-09 19:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0013_auto_20181209_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncierexpertise',
            name='montant_tb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='foncierexpertise',
            name='montant_tnb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
