# Generated by Django 2.0.7 on 2018-12-31 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0014_auto_20181209_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncierexpertise',
            name='annee',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
