# Generated by Django 2.0.7 on 2019-01-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0015_auto_20181231_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='foncieraccroissement',
            name='is_taux_annee_ecoulee',
            field=models.BooleanField(default=False),
        ),
    ]
