# Generated by Django 2.0.7 on 2019-01-11 06:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0016_foncieraccroissement_is_taux_annee_ecoulee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncierexpertise',
            name='montant_tb',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='foncierexpertise',
            name='montant_tnb',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='foncierimpot',
            name='accessibilite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Accessibilite'),
        ),
        migrations.AlterField(
            model_name='foncierparcelle',
            name='accessibilite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Accessibilite'),
        ),
        migrations.AlterField(
            model_name='fonciertnbimpot',
            name='accessibilite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Accessibilite'),
        ),
        migrations.DeleteModel(
            name='FoncierAccessibilite',
        ),
    ]
