# Generated by Django 2.0.7 on 2019-01-17 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0017_auto_20190111_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonciercaracteristique',
            name='annee_mise_valeur',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
