# Generated by Django 2.0.7 on 2019-01-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0018_fonciercaracteristique_annee_mise_valeur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoncierAccroissement',
        ),
    ]
