# Generated by Django 2.0.7 on 2019-02-01 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_foncier', '0019_delete_foncieraccroissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foncierexpertise',
            name='superficie_non_batie',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
