# Generated by Django 2.0.7 on 2022-04-05 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_foncier", "0025_auto_20220210_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="foncierexpertise",
            name="nbr_anne",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(4),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
