# Generated by Django 3.1.7 on 2022-02-09 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mod_documents.submodels.model_non_redevabilite


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_crm', '0006_auto_20190110_1254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonRedevabilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25, unique=True)),
                ('nombre_copie', models.PositiveSmallIntegerField(default=1)),
                ('validite', models.PositiveSmallIntegerField(default=1)),
                ('libelle', models.TextField(max_length=512)),
                ('fichier_authorization', models.FileField(null=True, upload_to=mod_documents.submodels.model_non_redevabilite.path_file_authorisation)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_note', models.DateTimeField(null=True)),
                ('reponse_note', models.CharField(blank=True, max_length=255, null=True)),
                ('demande_annulation_validation', models.BooleanField(default=False)),
                ('date_cancel', models.DateTimeField(null=True)),
                ('contribuable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mod_crm.contribuable')),
                ('user_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonredevabilite_requests_cancel', to=settings.AUTH_USER_MODEL)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonredevabilite_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonredevabilite_requests_note', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonredevabilite_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonredevabilite_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonredevabilite_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
