# Generated by Django 2.0.7 on 2018-10-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0005_auto_20181019_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisimposition',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noteimposition',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (1, 'Django-Model:Standard'), (5, 'Django-Model:AllocationEspacePublique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (10, 'Django-Model:FoncierParcelle'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (8, 'Django-Model:AllocationPlaceMarche'), (4, 'Django-Model:VisiteSiteTouristique'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (2, 'Django-Model:Marche')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (1, 'Django-Model:Standard'), (5, 'Django-Model:AllocationEspacePublique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (10, 'Django-Model:FoncierParcelle'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (8, 'Django-Model:AllocationPlaceMarche'), (4, 'Django-Model:VisiteSiteTouristique'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (2, 'Django-Model:Marche')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(9, 'Septembre'), (6, 'Juin'), (15, '3e Trimestre'), (2, 'Février'), (7, 'Juillet'), (12, 'Décembre'), (11, 'Novembre'), (10, 'Octobre'), (19, 'Année'), (14, '2e Trimestre'), (3, 'Mars'), (13, '1er Trimestre'), (4, 'Avril'), (18, '2e Semestre'), (5, 'Mai'), (8, 'Août'), (1, 'Janvier'), (17, '1er Semestre'), (16, '4e Timestre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(4, 'Annuelle'), (1, 'Mensuelle'), (3, 'Semestrielle'), (0, 'Autre'), (2, 'Trimestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
