# Generated by Django 2.0.7 on 2018-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0006_auto_20181023_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (5, 'Django-Model:AllocationEspacePublique'), (7, 'Django-Model:PubliciteMurCloture'), (2, 'Django-Model:Marche'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (15, 'Django-Model:FoncierParcelleDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (8, 'Django-Model:AllocationPlaceMarche')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (5, 'Django-Model:AllocationEspacePublique'), (7, 'Django-Model:PubliciteMurCloture'), (2, 'Django-Model:Marche'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (15, 'Django-Model:FoncierParcelleDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (8, 'Django-Model:AllocationPlaceMarche')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(14, '2e Trimestre'), (4, 'Avril'), (15, '3e Trimestre'), (3, 'Mars'), (11, 'Novembre'), (16, '4e Timestre'), (5, 'Mai'), (2, 'Février'), (7, 'Juillet'), (17, '1er Semestre'), (6, 'Juin'), (10, 'Octobre'), (12, 'Décembre'), (18, '2e Semestre'), (13, '1er Trimestre'), (8, 'Août'), (1, 'Janvier'), (19, 'Année'), (9, 'Septembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(3, 'Semestrielle'), (0, 'Autre'), (2, 'Trimestrielle'), (4, 'Annuelle'), (1, 'Mensuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
