# Generated by Django 2.0.7 on 2018-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0009_auto_20181023_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(1, 'Django-Model:Standard'), (2, 'Django-Model:Marche'), (10, 'Django-Model:FoncierParcelle'), (11, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture'), (4, 'Django-Model:VisiteSiteTouristique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(1, 'Django-Model:Standard'), (2, 'Django-Model:Marche'), (10, 'Django-Model:FoncierParcelle'), (11, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture'), (4, 'Django-Model:VisiteSiteTouristique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(11, 'Novembre'), (3, 'Mars'), (4, 'Avril'), (6, 'Juin'), (5, 'Mai'), (10, 'Octobre'), (8, 'Août'), (15, '3e Trimestre'), (16, '4e Timestre'), (17, '1er Semestre'), (1, 'Janvier'), (2, 'Février'), (7, 'Juillet'), (9, 'Septembre'), (12, 'Décembre'), (19, 'Année'), (18, '2e Semestre'), (13, '1er Trimestre'), (14, '2e Trimestre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (3, 'Semestrielle'), (4, 'Annuelle'), (1, 'Mensuelle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
