# Generated by Django 2.0.7 on 2018-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0029_auto_20181102_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(3, 'Django-Model:ActiviteExceptionnel'), (13, 'Django-Model:VehiculeProprietaire'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (1, 'Django-Model:Standard'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (4, 'Django-Model:VisiteSiteTouristique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(3, 'Django-Model:ActiviteExceptionnel'), (13, 'Django-Model:VehiculeProprietaire'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (1, 'Django-Model:Standard'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (4, 'Django-Model:VisiteSiteTouristique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(17, '1er Semestre'), (10, 'Octobre'), (14, '2e Trimestre'), (7, 'Juillet'), (6, 'Juin'), (3, 'Mars'), (2, 'Février'), (12, 'Décembre'), (19, 'Année'), (18, '2e Semestre'), (16, '4e Trimestre'), (4, 'Avril'), (13, '1er Trimestre'), (9, 'Septembre'), (15, '3e Trimestre'), (8, 'Août'), (5, 'Mai'), (1, 'Janvier'), (11, 'Novembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Mensuelle'), (3, 'Semestrielle'), (4, 'Annuelle'), (2, 'Trimestrielle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
