# Generated by Django 2.0.7 on 2018-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0030_auto_20181103_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (11, 'Django-Model:VehiculeActivite'), (12, 'Django-Model:VehiculeActivite'), (4, 'Django-Model:VisiteSiteTouristique'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (13, 'Django-Model:VehiculeProprietaire'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (5, 'Django-Model:AllocationEspacePublique'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (11, 'Django-Model:VehiculeActivite'), (12, 'Django-Model:VehiculeActivite'), (4, 'Django-Model:VisiteSiteTouristique'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (13, 'Django-Model:VehiculeProprietaire'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (5, 'Django-Model:AllocationEspacePublique'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(7, 'Juillet'), (16, '4e Trimestre'), (12, 'Décembre'), (10, 'Octobre'), (14, '2e Trimestre'), (11, 'Novembre'), (15, '3e Trimestre'), (9, 'Septembre'), (5, 'Mai'), (4, 'Avril'), (6, 'Juin'), (18, '2e Semestre'), (3, 'Mars'), (13, '1er Trimestre'), (8, 'Août'), (1, 'Janvier'), (17, '1er Semestre'), (2, 'Février'), (19, 'Année')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Mensuelle'), (3, 'Semestrielle'), (0, 'Autre'), (2, 'Trimestrielle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='taxe_filter',
            field=models.IntegerField(choices=[(0, "Autres Avis d'imposition"), (1, "Avis d'impositon - Administratif"), (2, "Avis d'impositon - Transport"), (3, 'Activite Standard-Marché'), (4, "Avis d'imposition - Activité exceptionnelle"), (5, "Avis d'imposition - Visite site touristique"), (6, 'Allocation Espace publique'), (7, 'Allocation panneau publicitaire'), (8, 'Publicité sur les murs et clôtures'), (11, 'Impôts fonciers'), (9, 'Allocation de place dans le marché'), (10, 'Location batiments municipaux'), (12, 'Activité sur les transports rémunérés'), (13, 'Droit de stationnement'), (14, 'Taxes sur les véhicule de propriété'), (15, 'Taxes sur les gros bétails')], default=0, verbose_name='Type de taxe'),
        ),
    ]
