# Generated by Django 2.0.7 on 2018-11-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0031_auto_20181105_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(1, 'Django-Model:Standard'), (2, 'Django-Model:Marche'), (8, 'Django-Model:AllocationPlaceMarche'), (13, 'Django-Model:VehiculeProprietaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (12, 'Django-Model:VehiculeActivite'), (9, 'Location batiments municipaux'), (18, 'Django-Model:BetailsPropriete'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (4, 'Django-Model:VisiteSiteTouristique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(1, 'Django-Model:Standard'), (2, 'Django-Model:Marche'), (8, 'Django-Model:AllocationPlaceMarche'), (13, 'Django-Model:VehiculeProprietaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (12, 'Django-Model:VehiculeActivite'), (9, 'Location batiments municipaux'), (18, 'Django-Model:BetailsPropriete'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (4, 'Django-Model:VisiteSiteTouristique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(17, '1er Semestre'), (10, 'Octobre'), (5, 'Mai'), (3, 'Mars'), (4, 'Avril'), (9, 'Septembre'), (15, '3e Trimestre'), (19, 'Année'), (18, '2e Semestre'), (12, 'Décembre'), (14, '2e Trimestre'), (1, 'Janvier'), (16, '4e Trimestre'), (13, '1er Trimestre'), (2, 'Février'), (8, 'Août'), (6, 'Juin'), (7, 'Juillet'), (11, 'Novembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (1, 'Mensuelle'), (4, 'Annuelle'), (0, 'Autre'), (3, 'Semestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
