# Generated by Django 2.0.7 on 2018-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0033_auto_20181105_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(7, 'Django-Model:PubliciteMurCloture'), (9, 'Location batiments municipaux'), (1, 'Django-Model:Standard'), (12, 'Django-Model:VehiculeActivite'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (13, 'Django-Model:VehiculeProprietaire'), (4, 'Django-Model:VisiteSiteTouristique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (2, 'Django-Model:Marche'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (3, 'Django-Model:ActiviteExceptionnel'), (8, 'Django-Model:AllocationPlaceMarche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(7, 'Django-Model:PubliciteMurCloture'), (9, 'Location batiments municipaux'), (1, 'Django-Model:Standard'), (12, 'Django-Model:VehiculeActivite'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (13, 'Django-Model:VehiculeProprietaire'), (4, 'Django-Model:VisiteSiteTouristique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (2, 'Django-Model:Marche'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (3, 'Django-Model:ActiviteExceptionnel'), (8, 'Django-Model:AllocationPlaceMarche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(5, 'Mai'), (2, 'Février'), (6, 'Juin'), (19, 'Année'), (10, 'Octobre'), (9, 'Septembre'), (13, '1er Trimestre'), (12, 'Décembre'), (14, '2e Trimestre'), (3, 'Mars'), (15, '3e Trimestre'), (11, 'Novembre'), (17, '1er Semestre'), (18, '2e Semestre'), (4, 'Avril'), (16, '4e Trimestre'), (8, 'Août'), (7, 'Juillet'), (1, 'Janvier')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Mensuelle'), (3, 'Semestrielle'), (2, 'Trimestrielle'), (4, 'Annuelle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
