# Generated by Django 2.0.7 on 2018-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0034_auto_20181105_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(5, 'Django-Model:AllocationEspacePublique'), (12, 'Django-Model:VehiculeActivite'), (7, 'Django-Model:PubliciteMurCloture'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (1, 'Django-Model:Standard'), (10, 'Django-Model:FoncierParcelle'), (14, 'Django-Model:BaseActiviteDuplicata'), (18, 'Django-Model:BetailsPropriete'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (15, 'Django-Model:FoncierParcelleDuplicata'), (9, 'Location batiments municipaux'), (8, 'Django-Model:AllocationPlaceMarche')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(5, 'Django-Model:AllocationEspacePublique'), (12, 'Django-Model:VehiculeActivite'), (7, 'Django-Model:PubliciteMurCloture'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (1, 'Django-Model:Standard'), (10, 'Django-Model:FoncierParcelle'), (14, 'Django-Model:BaseActiviteDuplicata'), (18, 'Django-Model:BetailsPropriete'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (15, 'Django-Model:FoncierParcelleDuplicata'), (9, 'Location batiments municipaux'), (8, 'Django-Model:AllocationPlaceMarche')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(6, 'Juin'), (2, 'Février'), (17, '1er Semestre'), (14, '2e Trimestre'), (4, 'Avril'), (12, 'Décembre'), (19, 'Année'), (8, 'Août'), (11, 'Novembre'), (18, '2e Semestre'), (7, 'Juillet'), (3, 'Mars'), (15, '3e Trimestre'), (1, 'Janvier'), (13, '1er Trimestre'), (16, '4e Trimestre'), (5, 'Mai'), (10, 'Octobre'), (9, 'Septembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (4, 'Annuelle'), (1, 'Mensuelle'), (3, 'Semestrielle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
