# Generated by Django 2.0.7 on 2018-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0039_auto_20181106_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(7, 'Django-Model:PubliciteMurCloture'), (11, 'Django-Model:VehiculeActivite'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (10, 'Django-Model:FoncierParcelle'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (1, 'Django-Model:Standard'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (2, 'Django-Model:Marche'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(7, 'Django-Model:PubliciteMurCloture'), (11, 'Django-Model:VehiculeActivite'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (10, 'Django-Model:FoncierParcelle'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (1, 'Django-Model:Standard'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (2, 'Django-Model:Marche'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(10, 'Octobre'), (14, '2e Trimestre'), (17, '1er Semestre'), (3, 'Mars'), (1, 'Janvier'), (18, '2e Semestre'), (16, '4e Trimestre'), (7, 'Juillet'), (2, 'Février'), (13, '1er Trimestre'), (15, '3e Trimestre'), (5, 'Mai'), (19, 'Année'), (11, 'Novembre'), (12, 'Décembre'), (6, 'Juin'), (9, 'Septembre'), (8, 'Août'), (4, 'Avril')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(3, 'Semestrielle'), (1, 'Mensuelle'), (4, 'Annuelle'), (2, 'Trimestrielle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='taxe_filter',
            field=models.IntegerField(choices=[(0, "Autres Avis d'imposition"), (1, "Avis d'impositon - Administratif"), (2, "Avis d'impositon - Transport"), (3, 'Activite Standard-Marché'), (4, "Avis d'imposition - Activité exceptionnelle"), (5, "Avis d'imposition - Visite site touristique"), (6, 'Allocation Espace publique'), (7, 'Allocation panneau publicitaire'), (8, 'Publicité sur les murs/clôtures'), (11, 'Impôts fonciers'), (9, 'Allocation de place dans le marché'), (10, 'Location batiments municipaux'), (12, 'Activité sur les transports rémunérés'), (13, 'Droit de stationnement'), (14, 'Taxes sur les véhicule de propriété'), (15, 'Taxes sur les gros bétails')], default=0, verbose_name='Type de taxe'),
        ),
    ]
