# Generated by Django 2.0.7 on 2018-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0049_auto_20181121_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteimposition',
            name='date_cancel',
        ),
        migrations.RemoveField(
            model_name='noteimposition',
            name='date_note',
        ),
        migrations.RemoveField(
            model_name='noteimposition',
            name='demande_annulation_validation',
        ),
        migrations.RemoveField(
            model_name='noteimposition',
            name='note',
        ),
        migrations.RemoveField(
            model_name='noteimposition',
            name='reponse_note',
        ),
        migrations.RemoveField(
            model_name='noteimposition',
            name='user_cancel',
        ),
        migrations.RemoveField(
            model_name='noteimposition',
            name='user_note',
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (10, 'Django-Model:FoncierParcelle'), (15, 'Django-Model:FoncierParcelleDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (7, 'Django-Model:PubliciteMurCloture'), (8, 'Django-Model:AllocationPlaceMarche'), (1, 'Django-Model:Standard'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (4, 'Django-Model:VisiteSiteTouristique'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (10, 'Django-Model:FoncierParcelle'), (15, 'Django-Model:FoncierParcelleDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (7, 'Django-Model:PubliciteMurCloture'), (8, 'Django-Model:AllocationPlaceMarche'), (1, 'Django-Model:Standard'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (4, 'Django-Model:VisiteSiteTouristique'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(5, 'Mai'), (6, 'Juin'), (4, 'Avril'), (3, 'Mars'), (14, '2e Trimestre'), (13, '1er Trimestre'), (9, 'Septembre'), (15, '3e Trimestre'), (17, '1er Semestre'), (7, 'Juillet'), (18, '2e Semestre'), (10, 'Octobre'), (19, 'Année'), (2, 'Février'), (12, 'Décembre'), (1, 'Janvier'), (16, '4e Trimestre'), (8, 'Août'), (11, 'Novembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(3, 'Semestrielle'), (4, 'Annuelle'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
