# Generated by Django 2.0.7 on 2018-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0052_auto_20181126_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (4, 'Django-Model:VisiteSiteTouristique'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (5, 'Django-Model:AllocationEspacePublique'), (7, 'Django-Model:PubliciteMurCloture'), (12, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (2, 'Django-Model:Marche'), (1, 'Django-Model:Standard'), (18, 'Django-Model:BetailsPropriete')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (4, 'Django-Model:VisiteSiteTouristique'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (5, 'Django-Model:AllocationEspacePublique'), (7, 'Django-Model:PubliciteMurCloture'), (12, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (2, 'Django-Model:Marche'), (1, 'Django-Model:Standard'), (18, 'Django-Model:BetailsPropriete')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(16, '4e Trimestre'), (8, 'Août'), (11, 'Novembre'), (12, 'Décembre'), (17, '1er Semestre'), (4, 'Avril'), (9, 'Septembre'), (18, '2e Semestre'), (2, 'Février'), (3, 'Mars'), (6, 'Juin'), (10, 'Octobre'), (19, 'Année'), (7, 'Juillet'), (15, '3e Trimestre'), (14, '2e Trimestre'), (5, 'Mai'), (1, 'Janvier'), (13, '1er Trimestre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Autre'), (3, 'Semestrielle'), (2, 'Trimestrielle'), (1, 'Mensuelle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
