# Generated by Django 2.0.7 on 2018-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0055_auto_20181205_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(2, 'Django-Model:Marche'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite'), (12, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (9, 'Location batiments municipaux'), (10, 'Django-Model:FoncierParcelle'), (4, 'Django-Model:VisiteSiteTouristique'), (13, 'Django-Model:VehiculeProprietaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (3, 'Django-Model:ActiviteExceptionnel'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(2, 'Django-Model:Marche'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite'), (12, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (9, 'Location batiments municipaux'), (10, 'Django-Model:FoncierParcelle'), (4, 'Django-Model:VisiteSiteTouristique'), (13, 'Django-Model:VehiculeProprietaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (3, 'Django-Model:ActiviteExceptionnel'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(4, 'Avril'), (17, '1er Semestre'), (8, 'Août'), (11, 'Novembre'), (3, 'Mars'), (19, 'Année'), (7, 'Juillet'), (15, '3e Trimestre'), (6, 'Juin'), (12, 'Décembre'), (5, 'Mai'), (9, 'Septembre'), (18, '2e Semestre'), (14, '2e Trimestre'), (13, '1er Trimestre'), (2, 'Février'), (16, '4e Trimestre'), (10, 'Octobre'), (1, 'Janvier')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (4, 'Annuelle'), (3, 'Semestrielle'), (0, 'Autre'), (1, 'Mensuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
