# Generated by Django 2.0.7 on 2018-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0059_auto_20181207_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (18, 'Django-Model:BetailsPropriete'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (18, 'Django-Model:BetailsPropriete'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(3, 'Mars'), (12, 'Décembre'), (1, 'Janvier'), (19, 'Année'), (6, 'Juin'), (4, 'Avril'), (5, 'Mai'), (8, 'Août'), (11, 'Novembre'), (14, '2e Trimestre'), (15, '3e Trimestre'), (16, '4e Trimestre'), (18, '2e Semestre'), (13, '1er Trimestre'), (10, 'Octobre'), (17, '1er Semestre'), (2, 'Février'), (7, 'Juillet'), (9, 'Septembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Autre'), (3, 'Semestrielle'), (2, 'Trimestrielle'), (1, 'Mensuelle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
