# Generated by Django 2.0.7 on 2018-12-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0062_auto_20181209_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (18, 'Django-Model:BetailsPropriete'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (8, 'Django-Model:AllocationPlaceMarche'), (3, 'Django-Model:ActiviteExceptionnel'), (10, 'Django-Model:FoncierParcelle'), (5, 'Django-Model:AllocationEspacePublique'), (4, 'Django-Model:VisiteSiteTouristique'), (12, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (18, 'Django-Model:BetailsPropriete'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (8, 'Django-Model:AllocationPlaceMarche'), (3, 'Django-Model:ActiviteExceptionnel'), (10, 'Django-Model:FoncierParcelle'), (5, 'Django-Model:AllocationEspacePublique'), (4, 'Django-Model:VisiteSiteTouristique'), (12, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(12, 'Décembre'), (14, '2e Trimestre'), (11, 'Novembre'), (3, 'Mars'), (6, 'Juin'), (8, 'Août'), (5, 'Mai'), (10, 'Octobre'), (19, 'Année'), (18, '2e Semestre'), (16, '4e Trimestre'), (4, 'Avril'), (1, 'Janvier'), (9, 'Septembre'), (17, '1er Semestre'), (15, '3e Trimestre'), (13, '1er Trimestre'), (7, 'Juillet'), (2, 'Février')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(3, 'Semestrielle'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (4, 'Annuelle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
