# Generated by Django 2.0.7 on 2018-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0064_auto_20181231_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique'), (18, 'Django-Model:BetailsPropriete'), (14, 'Django-Model:BaseActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (10, 'Django-Model:FoncierParcelle'), (5, 'Django-Model:AllocationEspacePublique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique'), (18, 'Django-Model:BetailsPropriete'), (14, 'Django-Model:BaseActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (10, 'Django-Model:FoncierParcelle'), (5, 'Django-Model:AllocationEspacePublique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(1, 'Janvier'), (6, 'Juin'), (4, 'Avril'), (14, '2e Trimestre'), (15, '3e Trimestre'), (3, 'Mars'), (19, 'Année'), (12, 'Décembre'), (16, '4e Trimestre'), (7, 'Juillet'), (18, '2e Semestre'), (10, 'Octobre'), (2, 'Février'), (8, 'Août'), (17, '1er Semestre'), (11, 'Novembre'), (5, 'Mai'), (13, '1er Trimestre'), (9, 'Septembre')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Mensuelle'), (0, 'Autre'), (2, 'Trimestrielle'), (4, 'Annuelle'), (3, 'Semestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
