# Generated by Django 2.0.7 on 2019-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0071_auto_20190104_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (12, 'Django-Model:VehiculeActivite'), (9, 'Location batiments municipaux'), (2, 'Django-Model:Marche'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (3, 'Django-Model:ActiviteExceptionnel'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (12, 'Django-Model:VehiculeActivite'), (9, 'Location batiments municipaux'), (2, 'Django-Model:Marche'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (3, 'Django-Model:ActiviteExceptionnel'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(14, '2e Trimestre'), (7, 'Juillet'), (19, 'Année'), (11, 'Novembre'), (8, 'Août'), (16, '4e Trimestre'), (9, 'Septembre'), (15, '3e Trimestre'), (17, '1er Semestre'), (1, 'Janvier'), (12, 'Décembre'), (18, '2e Semestre'), (10, 'Octobre'), (5, 'Mai'), (3, 'Mars'), (13, '1er Trimestre'), (2, 'Février'), (6, 'Juin'), (4, 'Avril')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(3, 'Semestrielle'), (0, 'Autre'), (2, 'Trimestrielle'), (4, 'Annuelle'), (1, 'Mensuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
