# Generated by Django 2.0.7 on 2019-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0079_auto_20190110_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(14, 'Django-Model:BaseActiviteDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (11, 'Django-Model:VehiculeActivite'), (2, 'Django-Model:Marche'), (1, 'Django-Model:Standard'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (12, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique'), (4, 'Django-Model:VisiteSiteTouristique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(14, 'Django-Model:BaseActiviteDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (11, 'Django-Model:VehiculeActivite'), (2, 'Django-Model:Marche'), (1, 'Django-Model:Standard'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (12, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique'), (4, 'Django-Model:VisiteSiteTouristique')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(1, 'Janvier'), (19, 'Année'), (10, 'Octobre'), (5, 'Mai'), (7, 'Juillet'), (15, '3e Trimestre'), (18, '2e Semestre'), (12, 'Décembre'), (17, '1er Semestre'), (6, 'Juin'), (14, '2e Trimestre'), (9, 'Septembre'), (3, 'Mars'), (11, 'Novembre'), (16, '4e Trimestre'), (13, '1er Trimestre'), (2, 'Février'), (4, 'Avril'), (8, 'Août')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(4, 'Annuelle'), (0, 'Autre'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (3, 'Semestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
