# Generated by Django 2.0.7 on 2019-01-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0088_auto_20190111_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(2, 'Django-Model:Marche'), (12, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (18, 'Django-Model:BetailsPropriete'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (7, 'Django-Model:PubliciteMurCloture'), (3, 'Django-Model:ActiviteExceptionnel'), (13, 'Django-Model:VehiculeProprietaire'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (11, 'Django-Model:VehiculeActivite'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(2, 'Django-Model:Marche'), (12, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (18, 'Django-Model:BetailsPropriete'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (7, 'Django-Model:PubliciteMurCloture'), (3, 'Django-Model:ActiviteExceptionnel'), (13, 'Django-Model:VehiculeProprietaire'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (11, 'Django-Model:VehiculeActivite'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(19, 'Année'), (18, '2e Semestre'), (4, 'Avril'), (1, 'Janvier'), (5, 'Mai'), (6, 'Juin'), (8, 'Août'), (11, 'Novembre'), (9, 'Septembre'), (7, 'Juillet'), (15, '3e Trimestre'), (17, '1er Semestre'), (12, 'Décembre'), (3, 'Mars'), (14, '2e Trimestre'), (10, 'Octobre'), (13, '1er Trimestre'), (16, '4e Trimestre'), (2, 'Février')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Autre'), (3, 'Semestrielle'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
