# Generated by Django 2.0.7 on 2019-01-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0097_auto_20190125_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(4, 'Django-Model:VisiteSiteTouristique'), (8, 'Django-Model:AllocationPlaceMarche'), (5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (11, 'Django-Model:VehiculeActivite'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (2, 'Django-Model:Marche'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(4, 'Django-Model:VisiteSiteTouristique'), (8, 'Django-Model:AllocationPlaceMarche'), (5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (11, 'Django-Model:VehiculeActivite'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (2, 'Django-Model:Marche'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(5, 'Mai'), (15, '3e Trimestre'), (7, 'Juillet'), (8, 'Août'), (12, 'Décembre'), (14, '2e Trimestre'), (16, '4e Trimestre'), (18, '2e Semestre'), (19, 'Année'), (10, 'Octobre'), (17, '1er Semestre'), (6, 'Juin'), (11, 'Novembre'), (2, 'Février'), (9, 'Septembre'), (4, 'Avril'), (3, 'Mars'), (13, '1er Trimestre'), (1, 'Janvier')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Mensuelle'), (0, 'Autre'), (3, 'Semestrielle'), (2, 'Trimestrielle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
