# Generated by Django 2.0.7 on 2019-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0107_auto_20190220_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (5, 'Django-Model:AllocationEspacePublique'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (1, 'Django-Model:Standard'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique'), (7, 'Django-Model:PubliciteMurCloture'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (5, 'Django-Model:AllocationEspacePublique'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (1, 'Django-Model:Standard'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique'), (7, 'Django-Model:PubliciteMurCloture'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(10, 'Octobre'), (19, 'Année'), (4, 'Avril'), (12, 'Décembre'), (7, 'Juillet'), (16, '4e Trimestre'), (8, 'Août'), (11, 'Novembre'), (3, 'Mars'), (18, '2e Semestre'), (14, '2e Trimestre'), (17, '1er Semestre'), (9, 'Septembre'), (13, '1er Trimestre'), (15, '3e Trimestre'), (2, 'Février'), (6, 'Juin'), (5, 'Mai'), (1, 'Janvier')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (4, 'Annuelle'), (1, 'Mensuelle'), (0, 'Autre'), (3, 'Semestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
