# Generated by Django 2.0.7 on 2019-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0108_auto_20190224_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(10, 'Django-Model:FoncierParcelle'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (2, 'Django-Model:Marche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (1, 'Django-Model:Standard'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique'), (18, 'Django-Model:BetailsPropriete'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(10, 'Django-Model:FoncierParcelle'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (2, 'Django-Model:Marche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (1, 'Django-Model:Standard'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique'), (18, 'Django-Model:BetailsPropriete'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(17, '1er Semestre'), (2, 'Février'), (3, 'Mars'), (1, 'Janvier'), (6, 'Juin'), (7, 'Juillet'), (9, 'Septembre'), (4, 'Avril'), (11, 'Novembre'), (12, 'Décembre'), (16, '4e Trimestre'), (14, '2e Trimestre'), (5, 'Mai'), (18, '2e Semestre'), (15, '3e Trimestre'), (19, 'Année'), (10, 'Octobre'), (13, '1er Trimestre'), (8, 'Août')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(4, 'Annuelle'), (3, 'Semestrielle'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
