# Generated by Django 2.0.7 on 2019-02-24 13:49

from django.db import migrations, models
import mod_finance.submodels.model_imposition


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0111_auto_20190224_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimposition',
            name='paiement_externe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noteimposition',
            name='paiement_externe_file',
            field=models.FileField(null=True, upload_to=mod_finance.submodels.model_imposition.path_bordereau_ni_file_externe),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.IntegerField(choices=[(4, 'Django-Model:VisiteSiteTouristique'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (18, 'Django-Model:BetailsPropriete'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.IntegerField(choices=[(4, 'Django-Model:VisiteSiteTouristique'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (18, 'Django-Model:BetailsPropriete'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(13, '1er Trimestre'), (16, '4e Trimestre'), (14, '2e Trimestre'), (1, 'Janvier'), (9, 'Septembre'), (10, 'Octobre'), (2, 'Février'), (17, '1er Semestre'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (18, '2e Semestre'), (8, 'Août'), (11, 'Novembre'), (19, 'Année'), (15, '3e Trimestre'), (4, 'Avril'), (12, 'Décembre'), (3, 'Mars')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (1, 'Mensuelle'), (3, 'Semestrielle'), (4, 'Annuelle'), (0, 'Autre')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
