# Generated by Django 2.0.7 on 2020-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0124_auto_20200508_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (11, 'Django-Model:VehiculeActivite'), (10, 'Django-Model:FoncierParcelle'), (2, 'Django-Model:Marche'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (12, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (1, 'Django-Model:Standard'), (4, 'Django-Model:VisiteSiteTouristique'), (9, 'Location batiments municipaux')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (11, 'Django-Model:VehiculeActivite'), (10, 'Django-Model:FoncierParcelle'), (2, 'Django-Model:Marche'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (12, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (1, 'Django-Model:Standard'), (4, 'Django-Model:VisiteSiteTouristique'), (9, 'Location batiments municipaux')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (11, 'Django-Model:VehiculeActivite'), (10, 'Django-Model:FoncierParcelle'), (2, 'Django-Model:Marche'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (12, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (1, 'Django-Model:Standard'), (4, 'Django-Model:VisiteSiteTouristique'), (9, 'Location batiments municipaux')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(19, 'ANNEE'), (17, '1er SEMESTRE'), (5, 'MAI'), (14, '2e TRIMESTRE'), (16, '4e TRIMESTRE'), (6, 'JUIN'), (4, 'AVRIL'), (8, 'AOUT'), (7, 'JUILLET'), (3, 'MARS'), (15, '3e TRIMESTRE'), (9, 'SEPTEMBRE'), (2, 'FEVRIER'), (10, 'OCTOBRE'), (1, 'JANVIER'), (18, '2e SEMESTRE'), (12, 'DECEMBRE'), (13, '1er TRIMESTRE'), (11, 'NOVEMBRE')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(2, 'Trimestrielle'), (0, 'Autre'), (3, 'Semestrielle'), (1, 'Mensuelle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
