# Generated by Django 4.0.1 on 2022-01-28 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_finance', '0128_auto_20210225_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Django-Model:AllocationPanneauPublicitaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (9, 'Location batiments municipaux'), (11, 'Django-Model:VehiculeActivite'), (1, 'Django-Model:Standard'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='annee',
            field=models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Django-Model:AllocationPanneauPublicitaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (9, 'Location batiments municipaux'), (11, 'Django-Model:VehiculeActivite'), (1, 'Django-Model:Standard'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='user_delete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_delete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='user_penalite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_penalite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='annee',
            field=models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2014), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Django-Model:AllocationPanneauPublicitaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (8, 'Django-Model:AllocationPlaceMarche'), (10, 'Django-Model:FoncierParcelle'), (9, 'Location batiments municipaux'), (11, 'Django-Model:VehiculeActivite'), (1, 'Django-Model:Standard'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (2, 'Django-Model:Marche'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='user_delete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_delete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(1, 'JANVIER'), (6, 'JUIN'), (2, 'FEVRIER'), (12, 'DECEMBRE'), (11, 'NOVEMBRE'), (18, '2e SEMESTRE'), (10, 'OCTOBRE'), (14, '2e TRIMESTRE'), (8, 'AOUT'), (19, 'ANNEE'), (5, 'MAI'), (15, '3e TRIMESTRE'), (13, '1er TRIMESTRE'), (4, 'AVRIL'), (9, 'SEPTEMBRE'), (16, '4e TRIMESTRE'), (17, '1er SEMESTRE'), (7, 'JUILLET'), (3, 'MARS')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Autre'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (3, 'Semestrielle'), (4, 'Annuelle')], default=0, verbose_name='catégorie de périodes'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxecategorie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
