# Generated by Django 3.1.7 on 2022-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0130_alter_avisimposition_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (11, 'Django-Model:VehiculeActivite'), (2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique')], null=True),
        ),
        migrations.AlterField(
            model_name='avisimposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (11, 'Django-Model:VehiculeActivite'), (2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (7, 'Django-Model:PubliciteMurCloture'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (11, 'Django-Model:VehiculeActivite'), (2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noteimpositionpaiement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operateur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(17, '1er SEMESTRE'), (6, 'JUIN'), (11, 'NOVEMBRE'), (7, 'JUILLET'), (5, 'MAI'), (3, 'MARS'), (12, 'DECEMBRE'), (18, '2e SEMESTRE'), (13, '1er TRIMESTRE'), (9, 'SEPTEMBRE'), (8, 'AOUT'), (4, 'AVRIL'), (2, 'FEVRIER'), (10, 'OCTOBRE'), (19, 'ANNEE'), (14, '2e TRIMESTRE'), (16, '4e TRIMESTRE'), (1, 'JANVIER'), (15, '3e TRIMESTRE')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(3, 'Semestrielle'), (0, 'Autre'), (1, 'Mensuelle'), (4, 'Annuelle'), (2, 'Trimestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxecategorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
