# Generated by Django 3.1.7 on 2022-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0131_auto_20220131_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='date_penalite',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='noteimposition',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='noteimpositiondelete',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (3, 'Django-Model:ActiviteExceptionnel'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (9, 'Location batiments municipaux'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique')], null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='element',
            field=models.IntegerField(choices=[(12, 'DECEMBRE'), (4, 'AVRIL'), (17, '1er SEMESTRE'), (5, 'MAI'), (14, '2e TRIMESTRE'), (10, 'OCTOBRE'), (9, 'SEPTEMBRE'), (7, 'JUILLET'), (18, '2e SEMESTRE'), (6, 'JUIN'), (2, 'FEVRIER'), (8, 'AOUT'), (15, '3e TRIMESTRE'), (1, 'JANVIER'), (19, 'ANNEE'), (3, 'MARS'), (11, 'NOVEMBRE'), (13, '1er TRIMESTRE'), (16, '4e TRIMESTRE')], verbose_name='Elements de période'),
        ),
        migrations.AlterField(
            model_name='periodetype',
            name='categorie',
            field=models.IntegerField(choices=[(4, 'Annuelle'), (0, 'Autre'), (1, 'Mensuelle'), (2, 'Trimestrielle'), (3, 'Semestrielle')], default=0, verbose_name='catégorie de périodes'),
        ),
    ]
