# Generated by Django 2.0.7 on 2019-01-04 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.IntegerField(choices=[(13, 'Django-Model:VehiculeProprietaire'), (1, 'Django-Model:Standard'), (7, 'Django-Model:PubliciteMurCloture'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (10, 'Django-Model:FoncierParcelle'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (12, 'Django-Model:VehiculeActivite'), (11, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (18, 'Django-Model:BetailsPropriete'), (5, 'Django-Model:AllocationEspacePublique'), (4, 'Django-Model:VisiteSiteTouristique'), (8, 'Django-Model:AllocationPlaceMarche')])),
                ('entity_id', models.PositiveSmallIntegerField()),
                ('note', models.CharField(max_length=255)),
                ('date_note', models.DateTimeField()),
                ('reponse_note', models.CharField(blank=True, max_length=255, null=True)),
                ('demande_annulation_validation', models.BooleanField(default=False)),
                ('date_cancel', models.DateTimeField(null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('user_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notearchive_requests_cancel', to=settings.AUTH_USER_MODEL)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notearchive_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notearchive_requests_note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='notearchive',
            unique_together={('entity', 'entity_id')},
        ),
        migrations.AlterIndexTogether(
            name='notearchive',
            index_together={('entity', 'entity_id')},
        ),
    ]
