# Generated by Django 2.0.7 on 2019-01-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_helpers', '0003_auto_20190104_1008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notearchive',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='notearchive',
            index_together=set(),
        ),
    ]
