# Generated by Django 2.0.7 on 2019-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_helpers', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notearchive',
            name='entity_id',
            field=models.IntegerField(),
        ),
    ]
