# Generated by Django 2.0.7 on 2018-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnephysique',
            name='sexe',
            field=models.IntegerField(choices=[(0, 'F'), (1, 'M')]),
        ),
    ]
