# Generated by Django 2.0.7 on 2019-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_crm', '0005_auto_20181115_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnemorale',
            name='type_caractere',
            field=models.IntegerField(choices=[(0, 'Commercial'), (1, 'Sans but lucratif'), (2, 'Co-propriétaire - Succession - etc.')], default=0),
        ),
    ]
