# Generated by Django 2.0.7 on 2018-10-11 09:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mod_activite.submodels.model_activite_arret_service
import mod_activite.submodels.model_activite_exceptionnelle
import mod_activite.submodels.model_allocation_espace_publique
import mod_activite.submodels.model_allocation_panneau_publicitaire
import mod_activite.submodels.model_allocation_place_marche
import mod_activite.submodels.model_publicite_mur_cloture
import mod_activite.submodels.model_visite_site_touristique


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_foncier', '0001_initial'),
        ('mod_finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_parametrage', '0001_initial'),
        ('mod_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteExceptionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_activite', models.CharField(max_length=30)),
                ('nom_beneficiaire', models.CharField(max_length=50)),
                ('motif_activite', models.CharField(max_length=255)),
                ('date_delivrance', models.DateTimeField()),
                ('date_expiration', models.DateTimeField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('ai_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.AvisImposition')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activiteexceptionnel_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activiteexceptionnel_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activiteexceptionnel_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activiteexceptionnel_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AllocationEspacePublique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_allocation', models.CharField(max_length=30)),
                ('reference_juridique', models.CharField(max_length=30, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('superficie', models.PositiveSmallIntegerField(default=0)),
                ('solde_depart', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fichier_lettre_exp_tmp', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_allocation_espace_publique.path_fichier_lettre_exp_tmp)),
                ('fichier_rap_vis_ter', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_allocation_espace_publique.path_fichier_rap_vis_ter)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
                ('parcelle_publique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_foncier.FoncierParcellePublique')),
                ('taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.Taxe')),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationespacepublique_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationespacepublique_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationespacepublique_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationespacepublique_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AllocationPanneauPublicitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_allocation', models.CharField(max_length=30)),
                ('reference_juridique', models.CharField(max_length=30, unique=True)),
                ('adresse_precise', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie', models.PositiveSmallIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('solde_depart', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fichier_lettre_exp_tmp', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_allocation_panneau_publicitaire.path_fichier_lettre_exp_tmp)),
                ('fichier_rap_vis_ter', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_allocation_panneau_publicitaire.path_fichier_rap_vis_ter)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Quartier')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
                ('numero_rueavenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.RueOuAvenue')),
                ('taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.Taxe')),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationpanneaupublicitaire_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationpanneaupublicitaire_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationpanneaupublicitaire_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationpanneaupublicitaire_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AllocationPlaceMarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('solde_depart', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fichier_contrat', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_allocation_place_marche.path_fichier_contrat_marche)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ArretService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=100)),
                ('fichier_formulaire_arret', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_activite_arret_service.path_fichier_formulaire_arret)),
                ('date_arret', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BaseActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_activite', models.CharField(max_length=30, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('solde_depart', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
                ('numero_carte_physique', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_impression', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DroitPlaceMarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_place', models.CharField(max_length=10, verbose_name='Place n°')),
                ('cout_place', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Coût')),
                ('occuped', models.BooleanField(default=False, verbose_name='Occupée')),
            ],
            options={
                'ordering': ('nom_marche', 'numero_place'),
            },
        ),
        migrations.CreateModel(
            name='NomMarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='PubliciteMurCloture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_allocation', models.CharField(max_length=30)),
                ('type_publicite', models.IntegerField(choices=[(0, 'Mur'), (1, 'Clôture')])),
                ('reference_juridique', models.CharField(max_length=30, unique=True)),
                ('adresse_precise', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie', models.PositiveSmallIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('solde_depart', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fichier_lettre_exp_tmp', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_publicite_mur_cloture.path_fichier_lettre_exp_tmp)),
                ('fichier_rap_vis_ter', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_publicite_mur_cloture.path_fichier_rap_vis_ter)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Quartier')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
                ('numero_rueavenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.RueOuAvenue')),
                ('taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.Taxe')),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicitemurcloture_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicitemurcloture_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicitemurcloture_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicitemurcloture_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_place', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VisiteSiteTouristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_visite', models.CharField(max_length=30)),
                ('nom_beneficiaire', models.CharField(max_length=50)),
                ('motif_visite', models.CharField(max_length=255)),
                ('date_delivrance', models.DateTimeField()),
                ('date_expiration', models.DateTimeField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('ai_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.AvisImposition')),
                ('site_touristique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_activite.SiteTouristique')),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitesitetouristique_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitesitetouristique_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitesitetouristique_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitesitetouristique_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('baseactivite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mod_activite.BaseActivite')),
            ],
            bases=('mod_activite.baseactivite',),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('baseactivite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mod_activite.BaseActivite')),
                ('type_espace', models.IntegerField(choices=[(0, 'Privée'), (1, 'Publique')], default=0)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Quartier')),
                ('allocation_espace_publique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mod_activite.AllocationEspacePublique')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
                ('numero_rueavenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.RueOuAvenue')),
            ],
            bases=('mod_activite.baseactivite',),
        ),
        migrations.AddField(
            model_name='droitplacemarche',
            name='nom_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_activite.NomMarche', verbose_name='Marché'),
        ),
        migrations.AddField(
            model_name='baseactivite',
            name='taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.Taxe'),
        ),
        migrations.AddField(
            model_name='baseactivite',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseactivite',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseactivite',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseactivite',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arretservice',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_activite.BaseActivite'),
        ),
        migrations.AddField(
            model_name='arretservice',
            name='user_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arretservice_requests_arret', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationplacemarche',
            name='droit_place_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_activite.DroitPlaceMarche'),
        ),
        migrations.AddField(
            model_name='allocationplacemarche',
            name='taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_finance.Taxe'),
        ),
        migrations.AddField(
            model_name='allocationplacemarche',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocationplacemarche_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationplacemarche',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationplacemarche_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationplacemarche',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationplacemarche_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationplacemarche',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocationplacemarche_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marche',
            name='allocation_place_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_activite.AllocationPlaceMarche'),
        ),
        migrations.AlterUniqueTogether(
            name='droitplacemarche',
            unique_together={('nom_marche', 'numero_place')},
        ),
        migrations.AlterIndexTogether(
            name='droitplacemarche',
            index_together={('nom_marche', 'numero_place')},
        ),
    ]
