# Generated by Django 2.0.7 on 2018-10-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0004_auto_20181023_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activiteexceptionnelle',
            old_name='nom_beneficiaire',
            new_name='beneficiaire',
        ),
    ]
