# Generated by Django 2.0.7 on 2018-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0005_auto_20181023_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
