# Generated by Django 2.0.7 on 2018-10-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0011_auto_20181024_0111'),
        ('mod_activite', '0006_activiteexceptionnelle_piece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitesitetouristique',
            old_name='nom_beneficiaire',
            new_name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='visitesitetouristique',
            name='ai_reference',
        ),
        migrations.AddField(
            model_name='visitesitetouristique',
            name='taxe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mod_finance.Taxe'),
            preserve_default=False,
        ),
    ]
