# Generated by Django 2.0.7 on 2018-10-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0013_auto_20181029_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationespacepublique',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
