# Generated by Django 2.0.7 on 2018-10-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0014_auto_20181031_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='droitplacemarche',
            old_name='occuped',
            new_name='occupee',
        ),
    ]
