# Generated by Django 2.0.7 on 2018-11-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0037_auto_20181106_1140'),
        ('mod_activite', '0015_auto_20181031_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseactivite',
            name='ai_cout_carte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_taxe_ai_cout_carte', to='mod_finance.Taxe', verbose_name='Coût de la carte professionnelle (AVIS)'),
            preserve_default=338,
        ),
        migrations.AlterField(
            model_name='baseactivite',
            name='taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_taxe_ai_cout_activite', to='mod_finance.Taxe', verbose_name="Coût de l'activité (NOTE)"),
        ),
    ]
