# Generated by Django 2.0.7 on 2018-11-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0016_auto_20181106_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseactivite',
            name='ai_cout_carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseactivite_requests_taxe_ai_cout_carte', to='mod_finance.Taxe', verbose_name='Coût de la carte professionnelle (AVIS)'),
        ),
    ]
