# Generated by Django 2.0.7 on 2018-11-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0017_auto_20181106_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='numero_police',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
