# Generated by Django 2.0.7 on 2018-11-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0018_standard_numero_police'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicitemurcloture',
            name='type_publicite',
            field=models.IntegerField(choices=[(0, 'Mur'), (1, 'Clôture')]),
        ),
    ]
