# Generated by Django 2.0.7 on 2018-11-19 09:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0020_auto_20181115_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activiteexceptionnelle',
            old_name='piece_nombre',
            new_name='piece_nombre_1',
        ),
        migrations.RenameField(
            model_name='activiteexceptionnelle',
            old_name='piece_tarif',
            new_name='piece_tarif_1',
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_nombre_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_nombre_3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_nombre_4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_nombre_5',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_tarif_2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_tarif_3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_tarif_4',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='activiteexceptionnelle',
            name='piece_tarif_5',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
