# Generated by Django 2.0.7 on 2018-12-05 14:26

from django.db import migrations, models
import mod_activite.submodels.model_allocation_place_marche


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0022_auto_20181205_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationplacemarche',
            name='caution_fichier',
            field=models.FileField(blank=True, max_length=255, null=True),
        ),
    ]
