# Generated by Django 2.0.7 on 2018-12-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0023_allocationplacemarche_caution_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationplacemarche',
            name='caution_fichier',
        ),
    ]
