# Generated by Django 2.0.7 on 2018-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0025_allocationplacemarche_caution_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationplacemarche',
            name='caution_payee',
            field=models.BooleanField(default=None),
        ),
    ]
