# Generated by Django 2.0.7 on 2019-01-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0026_auto_20181208_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='type_espace',
            field=models.IntegerField(choices=[(0, 'Privé'), (1, 'Public')], default=0),
        ),
    ]
