# Generated by Django 2.0.7 on 2019-03-25 09:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0027_auto_20190117_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationpanneaupublicitaire',
            name='superficie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
