# Generated by Django 2.0.7 on 2019-03-25 10:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0028_auto_20190325_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationespacepublique',
            name='superficie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
