# Generated by Django 3.1.4 on 2021-01-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0029_auto_20190325_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseactivite',
            name='actif',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
