# Generated by Django 3.1.7 on 2022-01-31 16:27

from django.db import migrations, models
import mod_activite.submodels.model_activite_arret_service


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0032_auto_20220131_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='arretservice',
            name='fichier_carte_arret',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=mod_activite.submodels.model_activite_arret_service.path_fichier_carte_arret),
        ),
    ]
