# Generated by Django 3.1.7 on 2022-02-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_activite', '0033_arretservice_fichier_carte_arret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arretservice',
            old_name='date_validate',
            new_name='date_update',
        ),
    ]
