# Generated by Django 2.0.7 on 2018-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='compte_propre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiculecategorie',
            name='has_compte_propre',
            field=models.BooleanField(default=False, verbose_name='Compte propre (sans activité mais qui paierait seulement le droit de stationnement)'),
        ),
    ]
