# Generated by Django 2.0.7 on 2019-02-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_transport', '0006_auto_20181115_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='locale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plaque',
            field=models.CharField(max_length=10),
        ),
    ]
