# Generated by Django 3.1.7 on 2022-01-31 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mod_transport.submodels.model_vehicule_arret_service
import mod_transport.submodels.model_vehicule_transfert


class Migration(migrations.Migration):

    dependencies = [
        ('mod_crm', '0006_auto_20190110_1254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_transport', '0012_vehiculeactivite_user_arret'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeTransfert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.BooleanField(default=True)),
                ('plaque', models.CharField(blank=True, max_length=10, null=True)),
                ('chassis', models.CharField(blank=True, max_length=17, null=True)),
                ('remunere', models.BooleanField(default=True)),
                ('compte_propre', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=False)),
                ('fichier_carterose', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_transfert.path_fichier_vehicule_carterose)),
                ('fichier_non_redevabilite', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_transfert.path_fichier_vehicule_non_redevabilite)),
                ('date_create', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('date_transfert', models.DateTimeField(null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_note', models.DateTimeField(null=True)),
                ('reponse_note', models.CharField(blank=True, max_length=255, null=True)),
                ('demande_annulation_validation', models.BooleanField(default=False)),
                ('date_cancel', models.DateTimeField(null=True)),
                ('contribuable_encien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuable_encien', to='mod_crm.contribuable')),
                ('contribuable_nouveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuable_nouveau', to='mod_crm.contribuable')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.vehiculemodele')),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_transport.vehiculesouscategorie')),
                ('user_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_cancel', to=settings.AUTH_USER_MODEL)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_note', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_transfert', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculetransfert_requests_validate', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mod_transport.vehicule')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArretVehiculeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=100)),
                ('fichier_formulaire_vehicule_arret', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_arret_service.path_fichier_formulaire_vehicule_arret)),
                ('fichier_cart_minispal', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_arret_service.path_fichier_cart_minispal)),
                ('date_arret', models.DateTimeField(null=True)),
                ('date_ouverture', models.DateField(null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_note', models.DateTimeField(null=True)),
                ('reponse_note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('demande_annulation_validation', models.BooleanField(default=False)),
                ('definitif', models.BooleanField(default=False)),
                ('etat_reouverture', models.BooleanField(default=False)),
                ('date_cancel', models.DateTimeField(null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.vehiculeactivite')),
                ('user_arret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arretvehiculeservice_requests_arret', to=settings.AUTH_USER_MODEL)),
                ('user_cancel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arretvehiculeservice_requests_cancel', to=settings.AUTH_USER_MODEL)),
                ('user_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arretvehiculeservice_requests_note', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arretvehiculeservice_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
