# Generated by Django 2.0.7 on 2018-10-11 09:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mod_transport.submodels.model_vehicule
import mod_transport.submodels.model_vehicule_activite


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_finance', '0001_initial'),
        ('mod_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=6)),
                ('chassis', models.CharField(blank=True, max_length=17, null=True)),
                ('remunere', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=False)),
                ('fichier_carterose', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule.path_fichier_vehicule_carterose)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VehiculeActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_activite', models.CharField(max_length=30, unique=True)),
                ('date_debut', models.DateField()),
                ('chassis', models.CharField(blank=True, max_length=17, null=True)),
                ('solde_depart', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fichier_carterose', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_activite.path_fichier_vehicule_activite_carterose)),
                ('fichier_autorisation', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_activite.path_fichier_vehicule_activite_autorisation)),
                ('motif', models.CharField(blank=True, max_length=100, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('fichier_formulaire_arret', models.FileField(blank=True, max_length=255, null=True, upload_to=mod_transport.submodels.model_vehicule_activite.path_fichier_formulaire_arret)),
                ('numero_carte_physique', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_impression', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactivite_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactivite_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactivite_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactivite_requests_validate', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.Vehicule')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeActiviteDuplicata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte_physique', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_impression', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactiviteduplicata_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactiviteduplicata_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactiviteduplicata_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactiviteduplicata_requests_validate', to=settings.AUTH_USER_MODEL)),
                ('vehicule_activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.VehiculeActivite')),
            ],
            options={
                'ordering': ('-date_create',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom de la catégorie des véhicules ')),
                ('type_roue', models.IntegerField(choices=[(0, 'pas de roue'), (1, '2 ou 3 roues'), (2, '4 roues')], verbose_name='Type de roue')),
            ],
            options={
                'ordering': ('nom', 'type_roue'),
            },
        ),
        migrations.CreateModel(
            name='VehiculeMarque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Marque du véhicule')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeModele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Modèle du véhicule')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.VehiculeMarque', verbose_name='Marque du véhicule')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeProprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=50, unique=True)),
                ('numero_carte_physique', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_impression', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_crm.Contribuable', verbose_name='Contribuable')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaire_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaire_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaire_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaire_requests_validate', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.Vehicule')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeProprietaireDuplicata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte_physique', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_impression', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('date_validate', models.DateTimeField(null=True)),
                ('date_print', models.DateTimeField(null=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaireduplicata_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_print', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaireduplicata_requests_print', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaireduplicata_requests_updated', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaireduplicata_requests_validate', to=settings.AUTH_USER_MODEL)),
                ('vehicule_proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.VehiculeProprietaire')),
            ],
            options={
                'ordering': ('-date_create',),
            },
        ),
        migrations.CreateModel(
            name='VehiculeSousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Sous-catégorie')),
                ('transport_commun', models.BooleanField(default=False, verbose_name='Si transport commun')),
                ('has_plaque', models.BooleanField(default=True, verbose_name='Avoir plaque')),
                ('ai_cout_carte_professionnelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculesouscategorie_requests_taxe_ai_cout_carte_professionnelle', to='mod_finance.Taxe', verbose_name='Coût de la carte professionnelle (AVIS)')),
                ('ai_cout_carte_propriete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculesouscategorie_requests_taxe_ai_cout_carte_propriete', to='mod_finance.Taxe', verbose_name='Coût de la carte de propriété (AVIS)')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.VehiculeCategorie', verbose_name='Catégorie')),
                ('taxe_activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculesouscategorie_requests_taxe_ni_activite', to='mod_finance.Taxe', verbose_name='Taxe sur activité (NOTE)')),
                ('taxe_proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculesouscategorie_requests_taxe_ni_proprietaire', to='mod_finance.Taxe', verbose_name='Taxe sur le propriétaire (NOTE)')),
                ('taxe_stationnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculesouscategorie_requests_taxe_ni_stationnement', to='mod_finance.Taxe', verbose_name='Droit de stationnement (NOTE)')),
            ],
            options={
                'ordering': ('categorie',),
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_transport.VehiculeModele'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_transport.VehiculeSousCategorie'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
    ]
