# Generated by Django 2.0.7 on 2018-11-15 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_transport', '0005_auto_20181029_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculeactivite',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculeactivite',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactivite_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculeactiviteduplicata',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculeactiviteduplicata',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactiviteduplicata_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculeproprietaire',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculeproprietaire',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaire_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculeproprietaireduplicata',
            name='date_cancel',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculeproprietaireduplicata',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeproprietaireduplicata_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
    ]
