# Generated by Django 2.0.7 on 2020-05-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0122_auto_20200507_1249'),
        ('mod_transport', '0009_remove_vehiculecategorie_has_compte_propre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculesouscategorie',
            name='ai_cout_duplicata_carte_professionnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculesouscategorie_requests_taxe_ai_cout_duplicata_carte_professionnelle', to='mod_finance.Taxe', verbose_name='Coût duplicata de la carte professionnelle (AVIS)'),
        ),
    ]
