# Generated by Django 3.1.4 on 2021-01-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_transport', '0011_auto_20210116_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculeactivite',
            name='user_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculeactivite_requests_arret', to=settings.AUTH_USER_MODEL),
        ),
    ]
