# Generated by Django 4.0.1 on 2022-01-28 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0129_alter_agence_id_alter_avisimposition_entity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_transport', '0012_vehiculeactivite_user_arret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_arret', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_ecriture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_ecriture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivite',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_arret', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_ecriture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_ecriture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactivitearret',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_ecriture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_ecriture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeactiviteduplicata',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculecategorie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculemarque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculemodele',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_ecriture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_ecriture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaire',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_cancel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_ecriture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_ecriture', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_print', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculeproprietaireduplicata',
            name='user_validate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_validate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='ai_cout_carte_professionnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_taxe_ai_cout_carte_professionnelle', to='mod_finance.taxe', verbose_name='Coût de la carte professionnelle (AVIS)'),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='ai_cout_carte_propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_taxe_ai_cout_carte_propriete', to='mod_finance.taxe', verbose_name='Coût de la carte de propriété (AVIS)'),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='ai_cout_duplicata_carte_professionnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_taxe_ai_cout_duplicata_carte_professionnelle', to='mod_finance.taxe', verbose_name='Coût duplicata de la carte professionnelle (AVIS)'),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='taxe_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_taxe_ni_activite', to='mod_finance.taxe', verbose_name='Taxe sur activité (NOTE)'),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='taxe_proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_taxe_ni_proprietaire', to='mod_finance.taxe', verbose_name='Taxe sur le propriétaire (NOTE)'),
        ),
        migrations.AlterField(
            model_name='vehiculesouscategorie',
            name='taxe_stationnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_taxe_ni_stationnement', to='mod_finance.taxe', verbose_name='Droit de stationnement (NOTE)'),
        ),
    ]
