# Generated by Django 2.0.7 on 2018-10-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='Numéro de la commune')),
                ('nom', models.CharField(max_length=25, unique=True, verbose_name='Nom de la commune')),
            ],
            options={
                'ordering': ('nom', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=15, verbose_name='Group')),
                ('cle', models.CharField(max_length=25, verbose_name='Clé')),
                ('valeur', models.CharField(max_length=50, verbose_name='Valeur')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
            ],
            options={
                'ordering': ('group', 'cle'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Message simple'), (1, "Demande d'autorisation")], default=0)),
                ('objet', models.CharField(max_length=50, verbose_name='Group')),
                ('entity', models.IntegerField(choices=[(5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (1, 'Django-Model:Standard'), (7, 'Django-Model:PubliciteMurCloture'), (12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (3, 'Django-Model:ActiviteExceptionnel'), (13, 'Django-Model:VehiculeProprietaire'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (9, 'Location batiments municipaux'), (4, 'Django-Model:VisiteSiteTouristique'), (2, 'Django-Model:Marche'), (11, 'Django-Model:VehiculeActivite')], null=True)),
                ('entity_id', models.PositiveSmallIntegerField(null=True)),
                ('message', models.CharField(max_length=255, verbose_name='Group')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Group')),
                ('date_validate', models.DateTimeField(null=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_validate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests_validate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_create',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='Numéro de la province')),
                ('nom', models.CharField(max_length=15, unique=True, verbose_name='Nom de la province')),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numéro du quartier')),
                ('nom', models.CharField(max_length=25, verbose_name='Nom du quartier')),
            ],
            options={
                'ordering': ('zone', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='RueOuAvenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de rue ou avenue')),
            ],
            options={
                'ordering': ('zone',),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='Numéro de la zone')),
                ('nom', models.CharField(max_length=25, unique=True, verbose_name='Nom de la zone')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Commune', verbose_name='Commune de la zone')),
            ],
            options={
                'ordering': ('commune', 'numero'),
            },
        ),
        migrations.AddField(
            model_name='rueouavenue',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Zone'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Zone', verbose_name='Zone du quartier'),
        ),
        migrations.AlterUniqueTogether(
            name='globalvariables',
            unique_together={('group', 'cle')},
        ),
        migrations.AlterIndexTogether(
            name='globalvariables',
            index_together={('group', 'cle')},
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Province', verbose_name='Province de la commune'),
        ),
        migrations.AlterUniqueTogether(
            name='rueouavenue',
            unique_together={('zone', 'nom')},
        ),
        migrations.AlterIndexTogether(
            name='rueouavenue',
            index_together={('zone', 'nom')},
        ),
    ]
