# Generated by Django 2.0.7 on 2018-10-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0019_auto_20181029_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(1, 'Django-Model:Standard'), (4, 'Django-Model:VisiteSiteTouristique'), (7, 'Django-Model:PubliciteMurCloture'), (12, 'Django-Model:VehiculeActivite'), (3, 'Django-Model:ActiviteExceptionnel'), (2, 'Django-Model:Marche'), (5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (15, 'Django-Model:FoncierParcelleDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (9, 'Location batiments municipaux'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (11, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (14, 'Django-Model:BaseActiviteDuplicata'), (18, 'Django-Model:BetailsPropriete')], null=True),
        ),
    ]
