# Generated by Django 2.0.7 on 2018-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0027_auto_20181102_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvariables',
            name='cle',
            field=models.CharField(max_length=50, verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='globalvariables',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (2, 'Django-Model:Marche'), (3, 'Django-Model:ActiviteExceptionnel'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (10, 'Django-Model:FoncierParcelle'), (4, 'Django-Model:VisiteSiteTouristique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (13, 'Django-Model:VehiculeProprietaire'), (8, 'Django-Model:AllocationPlaceMarche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (14, 'Django-Model:BaseActiviteDuplicata'), (1, 'Django-Model:Standard'), (11, 'Django-Model:VehiculeActivite')], null=True),
        ),
    ]
