# Generated by Django 2.0.7 on 2018-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0030_auto_20181103_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(17, 'Django-Model:VehiculeProprietaireDuplicata'), (15, 'Django-Model:FoncierParcelleDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (9, 'Location batiments municipaux'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (11, 'Django-Model:VehiculeActivite'), (12, 'Django-Model:VehiculeActivite'), (4, 'Django-Model:VisiteSiteTouristique'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (13, 'Django-Model:VehiculeProprietaire'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche'), (5, 'Django-Model:AllocationEspacePublique'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
    ]
