# Generated by Django 2.0.7 on 2018-11-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0040_auto_20181112_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(16, 'Django-Model:VehiculeActiviteDuplicata'), (9, 'Location batiments municipaux'), (7, 'Django-Model:PubliciteMurCloture'), (11, 'Django-Model:VehiculeActivite'), (1, 'Django-Model:Standard'), (8, 'Django-Model:AllocationPlaceMarche'), (15, 'Django-Model:FoncierParcelleDuplicata'), (18, 'Django-Model:BetailsPropriete'), (14, 'Django-Model:BaseActiviteDuplicata'), (2, 'Django-Model:Marche'), (3, 'Django-Model:ActiviteExceptionnel'), (5, 'Django-Model:AllocationEspacePublique'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (12, 'Django-Model:VehiculeActivite'), (4, 'Django-Model:VisiteSiteTouristique'), (13, 'Django-Model:VehiculeProprietaire'), (10, 'Django-Model:FoncierParcelle')], null=True),
        ),
    ]
