# Generated by Django 2.0.7 on 2018-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0056_auto_20181207_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(3, 'Django-Model:ActiviteExceptionnel'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (10, 'Django-Model:FoncierParcelle'), (12, 'Django-Model:VehiculeActivite'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (18, 'Django-Model:BetailsPropriete'), (15, 'Django-Model:FoncierParcelleDuplicata'), (9, 'Location batiments municipaux'), (7, 'Django-Model:PubliciteMurCloture'), (4, 'Django-Model:VisiteSiteTouristique'), (11, 'Django-Model:VehiculeActivite'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (13, 'Django-Model:VehiculeProprietaire'), (2, 'Django-Model:Marche')], null=True),
        ),
    ]
