# Generated by Django 2.0.7 on 2019-01-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0074_auto_20190108_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(8, 'Django-Model:AllocationPlaceMarche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (18, 'Django-Model:BetailsPropriete'), (15, 'Django-Model:FoncierParcelleDuplicata'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique'), (9, 'Location batiments municipaux'), (2, 'Django-Model:Marche'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (1, 'Django-Model:Standard'), (12, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (4, 'Django-Model:VisiteSiteTouristique'), (14, 'Django-Model:BaseActiviteDuplicata')], null=True),
        ),
        migrations.AddField(
            model_name='rueouavenue',
            name='accessibilite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mod_parametrage.Accessibilite'),
        ),
    ]
