# Generated by Django 2.0.7 on 2019-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0091_auto_20190213_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(13, 'Django-Model:VehiculeProprietaire'), (3, 'Django-Model:ActiviteExceptionnel'), (14, 'Django-Model:BaseActiviteDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (2, 'Django-Model:Marche'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (9, 'Location batiments municipaux'), (12, 'Django-Model:VehiculeActivite'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (11, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (8, 'Django-Model:AllocationPlaceMarche'), (1, 'Django-Model:Standard'), (5, 'Django-Model:AllocationEspacePublique'), (15, 'Django-Model:FoncierParcelleDuplicata')], null=True),
        ),
    ]
