# Generated by Django 2.0.7 on 2019-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0095_auto_20190224_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(5, 'Django-Model:AllocationEspacePublique'), (8, 'Django-Model:AllocationPlaceMarche'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (12, 'Django-Model:VehiculeActivite'), (15, 'Django-Model:FoncierParcelleDuplicata'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique'), (18, 'Django-Model:BetailsPropriete'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (1, 'Django-Model:Standard'), (14, 'Django-Model:BaseActiviteDuplicata'), (9, 'Location batiments municipaux')], null=True),
        ),
    ]
