# Generated by Django 2.0.7 on 2019-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0102_auto_20190325_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.IntegerField(choices=[(4, 'Django-Model:VisiteSiteTouristique'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (2, 'Django-Model:Marche'), (14, 'Django-Model:BaseActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (8, 'Django-Model:AllocationPlaceMarche'), (1, 'Django-Model:Standard'), (18, 'Django-Model:BetailsPropriete'), (10, 'Django-Model:FoncierParcelle'), (9, 'Location batiments municipaux'), (13, 'Django-Model:VehiculeProprietaire'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (5, 'Django-Model:AllocationEspacePublique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (16, 'Django-Model:VehiculeActiviteDuplicata')], null=True),
        ),
    ]
