# Generated by Django 2.0.7 on 2020-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0108_auto_20200507_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (12, 'Django-Model:VehiculeActivite'), (14, 'Django-Model:BaseActiviteDuplicata'), (10, 'Django-Model:FoncierParcelle'), (7, 'Django-Model:PubliciteMurCloture'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (3, 'Django-Model:ActiviteExceptionnel'), (2, 'Django-Model:Marche'), (9, 'Location batiments municipaux'), (5, 'Django-Model:AllocationEspacePublique'), (4, 'Django-Model:VisiteSiteTouristique'), (1, 'Django-Model:Standard'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (11, 'Django-Model:VehiculeActivite'), (18, 'Django-Model:BetailsPropriete'), (13, 'Django-Model:VehiculeProprietaire'), (8, 'Django-Model:AllocationPlaceMarche')], null=True),
        ),
    ]
