# Generated by Django 3.1.7 on 2022-02-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_parametrage', '0117_auto_20220131_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du département')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du Service')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Django-Model:FoncierParcelleDuplicata'), (4, 'Django-Model:VisiteSiteTouristique'), (7, 'Django-Model:PubliciteMurCloture'), (1, 'Django-Model:Standard'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (13, 'Django-Model:VehiculeProprietaire'), (18, 'Django-Model:BetailsPropriete'), (3, 'Django-Model:ActiviteExceptionnel'), (9, 'Location batiments municipaux'), (14, 'Django-Model:BaseActiviteDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (2, 'Django-Model:Marche'), (8, 'Django-Model:AllocationPlaceMarche'), (11, 'Django-Model:VehiculeActivite'), (5, 'Django-Model:AllocationEspacePublique'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (12, 'Django-Model:VehiculeActivite'), (10, 'Django-Model:FoncierParcelle')], null=True),
        ),
    ]
