# Generated by Django 3.1.7 on 2022-02-10 14:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mod_parametrage", "0121_auto_20220209_1604"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalite",
            name="is_taux_annee_ecoulee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="entity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (8, "Django-Model:AllocationPlaceMarche"),
                    (9, "Location batiments municipaux"),
                    (1, "Django-Model:Standard"),
                    (2, "Django-Model:Marche"),
                    (18, "Django-Model:BetailsPropriete"),
                    (10, "Django-Model:FoncierParcelle"),
                    (13, "Django-Model:VehiculeProprietaire"),
                    (7, "Django-Model:PubliciteMurCloture"),
                    (11, "Django-Model:VehiculeActivite"),
                    (12, "Django-Model:VehiculeActivite"),
                    (15, "Django-Model:FoncierParcelleDuplicata"),
                    (17, "Django-Model:VehiculeProprietaireDuplicata"),
                    (14, "Django-Model:BaseActiviteDuplicata"),
                    (6, "Django-Model:AllocationPanneauPublicitaire"),
                    (4, "Django-Model:VisiteSiteTouristique"),
                    (16, "Django-Model:VehiculeActiviteDuplicata"),
                    (5, "Django-Model:AllocationEspacePublique"),
                    (3, "Django-Model:ActiviteExceptionnel"),
                ],
                null=True,
            ),
        ),
    ]
