# Generated by Django 3.1.7 on 2022-06-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_finance', '0140_auto_20220614_1152'),
        ('mod_parametrage', '0125_auto_20220614_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Django-Model:Marche'), (4, 'Django-Model:VisiteSiteTouristique'), (6, 'Django-Model:AllocationPanneauPublicitaire'), (14, 'Django-Model:BaseActiviteDuplicata'), (5, 'Django-Model:AllocationEspacePublique'), (15, 'Django-Model:FoncierParcelleDuplicata'), (17, 'Django-Model:VehiculeProprietaireDuplicata'), (9, 'Location batiments municipaux'), (11, 'Django-Model:VehiculeActivite'), (13, 'Django-Model:VehiculeProprietaire'), (1, 'Django-Model:Standard'), (3, 'Django-Model:ActiviteExceptionnel'), (12, 'Django-Model:VehiculeActivite'), (16, 'Django-Model:VehiculeActiviteDuplicata'), (7, 'Django-Model:PubliciteMurCloture'), (10, 'Django-Model:FoncierParcelle'), (18, 'Django-Model:BetailsPropriete'), (8, 'Django-Model:AllocationPlaceMarche')], null=True),
        ),
        migrations.CreateModel(
            name='ReportFileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mod_finance.agence')),
            ],
        ),
    ]
