SUCCESS_CODE = "00"
GENERIC_ERROR_CODE = "01"
EXISTING_REFERENCE_ERROR_CODE = "02"
INVALID_AMOUNT_ERROR_CODE = "03"

SERVER_ERROR_CODE = "500"
INVALID_DATA_ERROR_CODE = "400"
NOT_FOUND_ERROR_CODE = "404"
